spring:
  schooldb:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: ''
      jdbc-url: jdbc:mysql://localhost:3306/school_db?createDatabaseIfNotExist=true
      username: root
  accountdb:
    datasource:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: ''
      jdbc-url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  userdb:
    datasource:
      password: ''
      jdbc-url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
  application:
    name: multiple-databases-app
server:
  port: '9090'